// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Network","status":true,"description":"Network Integration with socket.io","parameters":{"Server IP":"149.202.52.230","Server port":"3000"}},
{"name":"ItemBook","status":true,"description":"Displays detailed statuses of items.","parameters":{"Unknown Data":"??????","Price Text":"Price","Equip Text":"Equip","Type Text":"Type"}},
{"name":"MMO","status":true,"description":"MMORPG Devkit","parameters":{}},
{"name":"AltMenuScreen","status":true,"description":"Alternative menu screen layout.","parameters":{}}
];
